model-interface
Rehan-Organization/errp pull request #29
Opened 2023-03-20 12:26 UTC by pratikshagund

2023-03-21 05:09 UTC, rbaidABS requested changes

2023-03-21 05:09 UTC, rbaidABS commented on UI/src/app/enity/feedback.ts
> +  created_date?: Date;
created_date Naming convention...should be same as others..follow camel case convention

2023-03-21 07:07 UTC, rbaidABS submitted a review, later dismissed
Review comments fixed

2023-03-23 07:11 UTC, rehannawab approved these changes

2023-03-23 07:11 UTC, merged