Raise an Award and Award raised by me
Rehan-Organization/errp pull request #41
Opened 2023-03-23 13:31 UTC by Amruta1854

Raise an Award and Award raised by me are integrated and working.

2023-03-24 05:11 UTC, rbaidABS requested changes

2023-03-24 05:11 UTC, rbaidABS commented on Server/src/main/java/com/abs/errp/awardrequest/AwardRequestServiceImpl.java
> +		awardRequest.setAwardRequestStatus(0);
What does 0 status mean, externalize and use an Enum

2023-03-24 05:11 UTC, rbaidABS commented on Server/src/main/java/com/abs/errp/awardrequest/AwardRequestServiceImpl.java
> +			System.out.println(awardRequest.getAward());
Remove sysout

2023-03-24 05:11 UTC, rbaidABS commented on Server/src/main/java/com/abs/errp/awardtype/AwardTypePublicController.java
> +public class AwardTypePublicController {
What is Public? what does this do? Please find appropriate name

2023-03-24 05:11 UTC, rbaidABS commented on Server/src/main/java/com/abs/errp/entity/AwardRequest.java
> +	private ErrpUser submittedToId;
Naming convention - if it is of type ErrpUser should not have the name submittedToId - only submittedTo will indicate

2023-03-24 05:11 UTC, rbaidABS commented on UI/src/app/award/award.service.spec.ts
> +// describe('AwardService', () => {
why is this test file commented?

2023-03-27 06:23 UTC, rbaidABS requested changes

2023-03-27 06:23 UTC, rbaidABS commented on Server/src/main/java/com/abs/errp/awardrequest/AwardRequestServiceImpl.java
> +		awardRequest.setAwardRequestStatus(AwardRequestStatus.PENDING.ordinal());
This is a tight coupling between the position of the status defined in the enum. What will happen if the sequence in the enum is changed or If I add a new status right at the start in the enum? Please create enum with id , status mapping.

2023-03-27 06:23 UTC, rbaidABS commented on Server/src/main/java/com/abs/errp/awardrequest/AwardRequestStatus.java
> +public enum AwardRequestStatus {
There should be explicit mapping between Id and description of status

2023-03-27 09:19 UTC, rehannawab requested changes

2023-03-27 14:18 UTC, rehannawab approved these changes

2023-03-27 14:21 UTC, rehannawab approved these changes

2023-03-27 14:21 UTC, merged